//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FusePoCPublish.EsbProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pocesb.allocatesoftware.com", ConfigurationName="EsbProxy.SayHiEndpoint")]
    public interface SayHiEndpoint {
        
        // CODEGEN: Generating message contract since the operation SayHi is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://pocesb.allocatesoftware.com/SayHi", ReplyAction="*")]
        FusePoCPublish.EsbProxy.SayHiResponse SayHi(FusePoCPublish.EsbProxy.SayHiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pocesb.allocatesoftware.com/SayHi", ReplyAction="*")]
        System.Threading.Tasks.Task<FusePoCPublish.EsbProxy.SayHiResponse> SayHiAsync(FusePoCPublish.EsbProxy.SayHiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @in;
        
        public SayHiRequest() {
        }
        
        public SayHiRequest(string @in) {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @out;
        
        public SayHiResponse() {
        }
        
        public SayHiResponse(bool @out) {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SayHiEndpointChannel : FusePoCPublish.EsbProxy.SayHiEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SayHiEndpointClient : System.ServiceModel.ClientBase<FusePoCPublish.EsbProxy.SayHiEndpoint>, FusePoCPublish.EsbProxy.SayHiEndpoint {
        
        public SayHiEndpointClient() {
        }
        
        public SayHiEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SayHiEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayHiEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayHiEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FusePoCPublish.EsbProxy.SayHiResponse FusePoCPublish.EsbProxy.SayHiEndpoint.SayHi(FusePoCPublish.EsbProxy.SayHiRequest request) {
            return base.Channel.SayHi(request);
        }
        
        public bool SayHi(string @in) {
            FusePoCPublish.EsbProxy.SayHiRequest inValue = new FusePoCPublish.EsbProxy.SayHiRequest();
            inValue.@in = @in;
            FusePoCPublish.EsbProxy.SayHiResponse retVal = ((FusePoCPublish.EsbProxy.SayHiEndpoint)(this)).SayHi(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FusePoCPublish.EsbProxy.SayHiResponse> FusePoCPublish.EsbProxy.SayHiEndpoint.SayHiAsync(FusePoCPublish.EsbProxy.SayHiRequest request) {
            return base.Channel.SayHiAsync(request);
        }
        
        public System.Threading.Tasks.Task<FusePoCPublish.EsbProxy.SayHiResponse> SayHiAsync(string @in) {
            FusePoCPublish.EsbProxy.SayHiRequest inValue = new FusePoCPublish.EsbProxy.SayHiRequest();
            inValue.@in = @in;
            return ((FusePoCPublish.EsbProxy.SayHiEndpoint)(this)).SayHiAsync(inValue);
        }
    }
}
